<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Com_menu_model extends CI_Model
{

    public $table = 'com_menu';
    public $id = 'menu_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('menu_id', $q);
	$this->db->or_like('rules_id', $q);
	$this->db->or_like('parent_id', $q);
	$this->db->or_like('menu_name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('number', $q);
	$this->db->or_like('url', $q);
	$this->db->or_like('is_active', $q);
	$this->db->or_like('cu', $q);
	$this->db->or_like('cd', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('menu_id', $q);
	$this->db->or_like('rules_id', $q);
	$this->db->or_like('parent_id', $q);
	$this->db->or_like('menu_name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('number', $q);
	$this->db->or_like('url', $q);
	$this->db->or_like('is_active', $q);
	$this->db->or_like('cu', $q);
	$this->db->or_like('cd', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Com_menu_model.php */
/* Location: ./application/models/Com_menu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-07-16 09:57:37 */
/* http://harviacode.com */