<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class JobsModel extends CI_Model
{

    public $table = 'jr_jobs';
	 public $table_self = 'cov_self_assesment';
	public $table_notule = 'jr_notulen';
    public $id = 'id';
	public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('jobs_code', $q);
	$this->db->or_like('kry_id', $q);
	$this->db->or_like('jobs_tittle', $q);
	$this->db->or_like('jobs_desc', $q);
	$this->db->or_like('jobs_stat', $q);
	$this->db->or_like('jobs_date', $q);
	$this->db->or_like('jobs_week', $q);
	$this->db->or_like('cr_dt', $q);
	$this->db->or_like('cr_up', $q);
	$this->db->or_like('u_cr', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('jobs_code', $q);
	$this->db->or_like('kry_id', $q);
	$this->db->or_like('jobs_tittle', $q);
	$this->db->or_like('jobs_desc', $q);
	$this->db->or_like('jobs_stat', $q);
	$this->db->or_like('jobs_date', $q);
	$this->db->or_like('jobs_week', $q);
	$this->db->or_like('cr_dt', $q);
	$this->db->or_like('cr_up', $q);
	$this->db->or_like('u_cr', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
	
	 function insertSelf($data)
    {
        $this->db->insert($this->table_self, $data);
    }
	
	 function insert_notulen($data)
    {
        $this->db->insert($this->table_notule, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }
	
	function update_notulen($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table_notule, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file JobsModel.php */
/* Location: ./application/models/JobsModel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-20 08:48:09 */
/* http://harviacode.com */