<?php
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_SetKpi extends CI_Model
{

    public $table = 'st_kpi_sett';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }



    function get_count_kpi($params){

        $sql = "SELECT account_id,COUNT(*) AS jml FROM ps_holding WHERE inputDate BETWEEN ? AND ?
                GROUP BY account_id ORDER BY jml ASC ";
        $query = $this->db->query($sql,$params);
        if ($query->num_rows() > 0) {
            $result = $query->result_array();
            $query->free_result();
            return $result;
        } else {
            return NULL;
        }
    }



    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kpi_name', $q);
	$this->db->or_like('kpi_value', $q);
	$this->db->or_like('kpi_weight', $q);
	$this->db->or_like('dt_cr', $q);
	$this->db->or_like('u_dt', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kpi_name', $q);
	$this->db->or_like('kpi_value', $q);
	$this->db->or_like('kpi_weight', $q);
	$this->db->or_like('dt_cr', $q);
	$this->db->or_like('u_dt', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_SetKpi.php */
/* Location: ./application/models/M_SetKpi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-17 09:59:54 */
/* http://harviacode.com */